# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canopy < Formula
  desc "Terminal UI for tracking tasks across work management backends"
  homepage "https://github.com/alcxyz/canopy"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alcxyz/canopy/releases/download/v0.2.1/canopy_0.2.1_darwin_amd64.tar.gz"
      sha256 "d262d25e00623b10b134dc803e3da1c1a8f9b5c34c24d3f68d59152a83e01fb6"

      define_method(:install) do
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alcxyz/canopy/releases/download/v0.2.1/canopy_0.2.1_darwin_arm64.tar.gz"
      sha256 "ce1aca419ab9482891f9eeef4db2a2aa041f85b2e3f9cdbd9d8b6f7cc7ec8a86"

      define_method(:install) do
        bin.install "canopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/canopy/releases/download/v0.2.1/canopy_0.2.1_linux_amd64.tar.gz"
      sha256 "19cd236be1c1d7a01e175b04ed3ec004ee1acdddd8a0239394531ccfc8e0d7cc"
      define_method(:install) do
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/canopy/releases/download/v0.2.1/canopy_0.2.1_linux_arm64.tar.gz"
      sha256 "efe3d6ffe85721ad00454f3a00bc7c6c43b733d9f03952a94cf2822da012cb5b"
      define_method(:install) do
        bin.install "canopy"
      end
    end
  end
end
