# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Terminal UI for monitoring GitHub repositories"
  homepage "https://github.com/alcxyz/grove"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alcxyz/grove/releases/download/v0.4.1/grove_0.4.1_darwin_amd64.tar.gz"
      sha256 "a604693a114b03e571c27d4b39bb0d04cc822394949ccefcebb2e05f71f560ab"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alcxyz/grove/releases/download/v0.4.1/grove_0.4.1_darwin_arm64.tar.gz"
      sha256 "d76f455f8237d21ab4549c839fe847cdb66380c4fae6c8de8c3a9869b905be01"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/grove/releases/download/v0.4.1/grove_0.4.1_linux_amd64.tar.gz"
      sha256 "ca18c5049de8f1b2e8060392dcadc27c22eb69b53e756c3c17f38adf6e315c09"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/grove/releases/download/v0.4.1/grove_0.4.1_linux_arm64.tar.gz"
      sha256 "17c414dc48d72571e71bfcf8bdb80240c68c04eb344d546f5ee0f8b9097604dd"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end
end
