# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Terminal UI for monitoring GitHub repositories"
  homepage "https://github.com/alcxyz/grove"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alcxyz/grove/releases/download/v0.5.0/grove_0.5.0_darwin_amd64.tar.gz"
      sha256 "4af63679a4b212f09946407877c6053b7907cbce61f0153803c43dd174561536"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alcxyz/grove/releases/download/v0.5.0/grove_0.5.0_darwin_arm64.tar.gz"
      sha256 "6d99fb1207145b4d5e9251f1bf7b9c3989164dd8878e5dd66326d30e1e9a759a"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/grove/releases/download/v0.5.0/grove_0.5.0_linux_amd64.tar.gz"
      sha256 "7fe4845e440bf5816e2b3041f9f21e8c71b2c5936fe819b3db6b1f662276840a"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/grove/releases/download/v0.5.0/grove_0.5.0_linux_arm64.tar.gz"
      sha256 "dbe9a0b00950d4791b79bf818ac53978dbc57669bb440b984d73ce3801effa17"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end
end
