# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Terminal UI for monitoring GitHub repositories"
  homepage "https://github.com/alcxyz/grove"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alcxyz/grove/releases/download/v0.5.0/grove_0.5.0_darwin_amd64.tar.gz"
      sha256 "22035641546ce868723e3e84681f3d57be99f6c33aac4d9648332bf345e58982"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alcxyz/grove/releases/download/v0.5.0/grove_0.5.0_darwin_arm64.tar.gz"
      sha256 "dfaa174d9983f2a2186241ebc49b5c94a0b2031e87e7020b3465dc2022f4f41d"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/grove/releases/download/v0.5.0/grove_0.5.0_linux_amd64.tar.gz"
      sha256 "2ac0a7a6081f07ed26fe72ed9131b280ced2f5a263cbf5f429d95ba78e103b2b"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/grove/releases/download/v0.5.0/grove_0.5.0_linux_arm64.tar.gz"
      sha256 "8759b757f5d76cb75e8f1861b76d3e61805a2125081b497df1211e1789bf9de3"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end
end
