# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paperflow < Formula
  desc "File organizer and Paperless-ngx ingestion tool"
  homepage "https://github.com/alcxyz/paperflow"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alcxyz/paperflow/releases/download/v0.3.1/paperflow_0.3.1_darwin_amd64.tar.gz"
      sha256 "2093b198332c0fc3b2d786b91cd1de2306b29bc67d97dc6a5df513ec2baa601a"

      define_method(:install) do
        bin.install "paperflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alcxyz/paperflow/releases/download/v0.3.1/paperflow_0.3.1_darwin_arm64.tar.gz"
      sha256 "0c57de03b24f63b02732685fc10324faa8b6365f3c2786d5b0be46e5cb88c923"

      define_method(:install) do
        bin.install "paperflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/paperflow/releases/download/v0.3.1/paperflow_0.3.1_linux_amd64.tar.gz"
      sha256 "aea8809850d407e53e3c087c3f5ebe3eaa153def518d7cb1ac16e101c73b7674"
      define_method(:install) do
        bin.install "paperflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcxyz/paperflow/releases/download/v0.3.1/paperflow_0.3.1_linux_arm64.tar.gz"
      sha256 "795561d029cd30b62d845749bc3641b91e2c26ad7c076e5d54b12c0828a7e148"
      define_method(:install) do
        bin.install "paperflow"
      end
    end
  end
end
